### PR TITLE
Upgrade django saml2 to 0.17.1

### PR DESCRIPTION
**Pull request by stuaxo**
[DO NOT MERGE - Without validating]

Since pysaml2 made changes to the XML, this should be validated against IDPs on UAT before merging.

### CODE REVIEW

**Comment by stuaxo** [comment]
XML changes on this branch

- [ ] Harmless (e.g. add/remove space between attribute and end tag)
- [ ] Namespace changes

    https://github.com/uktrade/staff-sso/pull/151/files#diff-2d94697d223bbc2babb93a51668ff1a7
    Could this affect the IDPs - or is this just XML we roundtrip to/from SSO ?


Failing test

SignatureError is not raised, in the test below - the test could check for the 403 status that the client gets, but will this cause a bug somewhere else ?

https://github.com/uktrade/staff-sso/blob/upgrade-djangosaml2-0.17.1/sso/tests/test_auth_flow.py#L356

**Comment by stuaxo** [comment]
As an outstanding thing, we should set SAML_DJANGO_USER_MAIN_ATTRIBUTE_LOOKUP to something meaningful, but I don't know what it should be yet.

**Comment by stuaxo** [comment]
Hi @marcofucci 

I've been trying to work out why the test here doesn't pass with djangosaml 4.5.0 and pysaml 0.16.4 (and up)

https://github.com/uktrade/staff-sso/blob/master/sso/tests/test_auth_flow.py#L354

Although the mock is set -

```
MockCryptoBackendXmlSec1 = mocker.patch('saml2.sigver.CryptoBackendXmlSec1', spec=True)
MockCryptoBackendXmlSec1().validate_signature.return_value = False
```

By the time ```validate_signature.return_value``` [is called](https://github.com/IdentityPython/pysaml2/blob/master/src/saml2/sigver.py#L1435), it returns True.   It is being mocked, as it is an instanceof MockCryptoBackendXmlSec1.

Any idea whats going on ?

**Comment by marcofucci** [comment]
@stuaxo I think it's caught here: https://github.com/knaperek/djangosaml2/blob/master/djangosaml2/views.py#L278 and it returns 403?

**Comment by stuaxo** [comment]
@marcofucci yes :) obvious when you see it... cheers, was having difficulty seeing that, thought it might be my lack of MagicMock experience.

**Pull request closed without merging**
