### PR TITLE
Remove pip-tools dep

### PR DESCRIPTION
**Pull request by marcofucci**
pip-tools doesn't manage different requirements easily and it doesn't have a nice workflow (pip-compile and pip-sync) so sticking to classic requirements.txt files.

### CODE REVIEW

**Comment by marcofucci** [comment]
@r4vi what do you think?

**Comment by marcofucci** [comment]
Otherwise, we could have 2 files:

`requirements.in`
`requirements-dev.in` with _-r requirements.txt_ in it

But every time we add/change a prod lib we have to:

_add/change the lib to requirements.in_
`pip-compile requirements.in` to generate the `requirements.txt`
`pip-compile -o requirements-dev.txt requirements-dev.in` to generate the `requirements-dev.txt`
`pip-sync requirements-dev.txt`

Whilst if we have to add/change a dev lib we _only_ need to do:

_add/change the lib to requirements-dev.in_
`pip-compile -o requirements-dev.txt requirements-dev.in` to generate the `requirements-dev.txt`
`pip-sync requirements-dev.txt`

**Comment by r4vi** [comment]
@marcofucci let's try your idea but I think we might not like not being able to install random libraries locally but maybe by then pipfile will be ready

**Comment by marcofucci** [comment]
@r4vi have a look

**Pull request merged**
