### PR TITLE
update pysaml2 and httplib2

### PR DESCRIPTION
**Pull request by dahfool**

### CODE REVIEW

**Comment by dahfool** [comment]
> need to change requirements .in please
> also change log update

These libs are not requirement.in and there are no changelog file.

**Comment by depsiatwal** [comment]
need to change .in file them compile the requirements 
https://github.com/uktrade/staff-sso/blob/vulnerabilities-fix/requirements-dev.in
https://github.com/uktrade/staff-sso/blob/vulnerabilities-fix/requirements.in

**Comment by dahfool** [comment]
> need to change .in file them compile the requirements
> https://github.com/uktrade/staff-sso/blob/vulnerabilities-fix/requirements-dev.in
> https://github.com/uktrade/staff-sso/blob/vulnerabilities-fix/requirements.in

pysaml2 and httplib2 are not in these 2 files, do i need to add them ?

**Comment by depsiatwal** [comment]
checking the compile requirements file looks like they imported because the are required by 
via google-api-python-client, google-auth-httplib2, oauth2client might need to check py-pi if there's any later versions that move away from the offending lib.

**Comment by lgarvey** [comment]
@dahfool yes you can add the pinned version directly into requirements.in, then regenerate the .txt files.

**Pull request closed without merging**
